### ISSUE TITLE
Fix responsiveness of actual block page

### ISSUE THREAD

**Issue by ansonyuu** [getreflect/reflect-chrome#40]
Fix main block page not being responsive. Right now, the main block page looks fine on larger screens:
![image](https://user-images.githubusercontent.com/23178940/91769779-dcc7f300-eb94-11ea-9211-428a557052b3.png)

but on smaller screens:
![image](https://user-images.githubusercontent.com/23178940/91769883-08e37400-eb95-11ea-8321-ad74270bee50.png)

**Comment by jackyzha0** [comment]
fix main block page not being responsive (looks kinda garbo on small screens)
