### ISSUE TITLE
Resolving url's from redirects before letting reflect intervene

### ISSUE THREAD

**Issue by OmarG247** [getreflect/reflect-chrome#62]
Noticed this today as I tried opening a link a friend send me on messenger. reflect thought I was going to facebook but this was just the wrapper that facebook puts on messenger links 

i.e. https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.reddit.com%2Fr%2Faww%2Fcomments%2Fgl5xg5%2Fonce_you_run_into_a_glass_door_you_develop_trust%2F&h=AT1x6960Xt941fCiwH42QnK1m5fejFGi7hreqtjdgYOfHZCNtyZOzxOb2fF-Xqy3wRi12tOkwmRb4bkuGM8OuvY_TqIpxZ0xLEgEPysyoBegg6TKg8bHgJAg6IyFlcCk-r4_YTTXEevn3QQ&s=1

**Comment by jackyzha0** [comment]
Thanks for the report! Was able to reproduce on reflect 1.2.0. You should see this fixed in the next major update :))

**Comment by OmarG247** [comment]
No worries! Looking forward to it :)
