### ISSUE TITLE
Issues with subdomains

### ISSUE THREAD

**Issue by LeptoFlare** [getreflect/reflect-chrome#97]
There are a couple of issues I've run into while trying to block specific subdomains.

1. Blocking the subdomain `www` will result in nothing getting blocked at all (`www.youtube.com`)
2. Blocking a domain will block all subdomains, there is no way to configure it. Despite this, if you navigate to a blocked page on a subdomain, the extension will ask you if you want to block the page, even though it shows it as blocked.
![image](https://user-images.githubusercontent.com/47790183/111395255-ca298d00-8692-11eb-87bb-762f5bfffd0f.png)

I'd like a way to block just `youtube.com` but not `music.youtube.com`

Regardless, this extension is severely underrated, and I'm really impressed with both the idea and the execution. o7/

**Comment by jackyzha0** [comment]
another bump on this from an email request, we should def try to prioritize this soon

> Hi! I just started using reflect but found an error that I was hoping you guys could fix. I blocked youtube, but my default music platform is youtube music (which uses the url music.youtube.com). It automatically gets blocked every time even though it's ~technically~ a different website. I was wondering if you guys could get this fixed since it may also apply to other websites that use the [ ___.website.com] format. One potential fix could be having a whitelisted sites list (saw this on another extension) where users could input the websites that they want whitelisted that might be blocked due to the url.

**Comment by jackyzha0** [comment]
## Acceptance Criteria
- [ ] Be able to block subdomains properly
- [ ] Query strings work properly
